// cmd/wire_gen.go
// Code generated by Wire. DO NOT EDIT.
//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kostinp/edu-platform-backend/internal/shared/config"
	"github.com/kostinp/edu-platform-backend/internal/shared/db"
	"github.com/kostinp/edu-platform-backend/internal/user"
	"github.com/kostinp/edu-platform-backend/internal/shared/abac"
	"github.com/kostinp/edu-platform-backend/internal/user/repository"
	"github.com/kostinp/edu-platform-backend/internal/user/transport/http"
	"github.com/kostinp/edu-platform-backend/internal/user/usecase"
	category_repository "github.com/kostinp/edu-platform-backend/internal/category/repository"
	category_usecase "github.com/kostinp/edu-platform-backend/internal/category/usecase"
	category_http "github.com/kostinp/edu-platform-backend/internal/category/transport/http"
	course_repository "github.com/kostinp/edu-platform-backend/internal/course/repository"
	course_usecase "github.com/kostinp/edu-platform-backend/internal/course/usecase"
	course_http "github.com/kostinp/edu-platform-backend/internal/course/transport/http"
	lesson_repository "github.com/kostinp/edu-platform-backend/internal/lesson/repository"
	lesson_usecase "github.com/kostinp/edu-platform-backend/internal/lesson/usecase"
	lesson_http "github.com/kostinp/edu-platform-backend/internal/lesson/transport/http"
	module_repository "github.com/kostinp/edu-platform-backend/internal/module/repository"
	module_usecase "github.com/kostinp/edu-platform-backend/internal/module/usecase"
	module_http "github.com/kostinp/edu-platform-backend/internal/module/transport/http"
	tag_repository "github.com/kostinp/edu-platform-backend/internal/tag/repository"
	tag_usecase "github.com/kostinp/edu-platform-backend/internal/tag/usecase"
	tag_http "github.com/kostinp/edu-platform-backend/internal/tag/transport/http"
	search_repository "github.com/kostinp/edu-platform-backend/internal/search/repository"
	search_usecase "github.com/kostinp/edu-platform-backend/internal/search/usecase"
	search_http "github.com/kostinp/edu-platform-backend/internal/search/transport/http"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/kostinp/edu-platform-backend/docs"
)

// Injectors from wire.go:
// Главный wire-компонент
func InitializeServer(cfg *config.Config, abacEngine *abac.Engine) (*echo.Echo, error) {
	pool := db.ConnectPostgres(cfg)
	postgresUserRepository := repository.NewPostgresUserRepository(pool)
	postgresSessionRepository := repository.NewPostgresSessionRepository(pool)
	sessionUsecaseImpl := usecase.NewSessionUsecase(postgresSessionRepository)
	userService := usecase.NewUserService(postgresUserRepository, sessionUsecaseImpl)
	userHandler := transport.NewUserHandler(userService)
	conn := user.ProvideClickHouseConn(cfg)
	clickHouseVisitorEventRepo := repository.NewClickHouseVisitorEventRepo(conn)
	visitorEventRepoWithFallback := repository.NewVisitorEventRepoWithFallback(clickHouseVisitorEventRepo, nil)
	visitorEventUsecase := usecase.NewVisitorEventUsecase(visitorEventRepoWithFallback)
	visitorEventHandler := transport.NewVisitorEventHandler(visitorEventUsecase)
	botToken := user.ProvideBotToken(cfg)
	jwtSecret := user.ProvideJwtSecret(cfg)
	telegramAuthHandler := transport.NewTelegramAuthHandler(userService, botToken, jwtSecret)
	sessionHandler := transport.NewSessionHandler(sessionUsecaseImpl)
	analyticsRepo := clickHouseVisitorEventRepo
	if !cfg.Analytics.Enabled {
		analyticsRepo = nil
	}
	analyticsHandler := transport.NewAnalyticsHandler(analyticsRepo)
	// Course
	postgresCourseRepository := course_repository.NewPostgresCourseRepository(pool)
	courseUsecase := course_usecase.NewCourseUsecase(postgresCourseRepository)
	courseHandler := course_http.NewCourseHandler(courseUsecase)
	// Module
	postgresModuleRepository := module_repository.NewPostgresModuleRepository(pool)
	moduleUsecase := module_usecase.NewModuleUsecase(postgresModuleRepository)
	moduleHandler := module_http.NewModuleHandler(moduleUsecase)
	// Lesson
	postgresLessonRepository := lesson_repository.NewPostgresLessonRepository(pool)
	lessonUsecase := lesson_usecase.NewLessonUsecase(postgresLessonRepository)
	lessonHandler := lesson_http.NewLessonHandler(lessonUsecase)
	// Category
	postgresCategoryRepository := category_repository.NewPostgresCategoryRepository(pool)
	categoryUsecase := category_usecase.NewCategoryUsecase(postgresCategoryRepository)
	postgresCategoryAssignmentRepository := category_repository.NewPostgresCategoryAssignmentRepository(pool)
	categoryAssignmentUsecase := category_usecase.NewCategoryAssignmentUsecase(postgresCategoryAssignmentRepository)
	postgresCategoryNavigationRepository := category_repository.NewPostgresCategoryNavigationRepository(pool)
	categoryNavigationUsecase := category_usecase.NewCategoryNavigationUsecase(postgresCategoryNavigationRepository)
	categoryHandler := category_http.NewCategoryHandler(categoryUsecase, categoryAssignmentUsecase)
	categoryNavigationHandler := category_http.NewCategoryNavigationHandler(categoryNavigationUsecase)
	// Tag
	postgresTagRepository := tag_repository.NewPostgresTagRepository(pool)
	tagUsecase := tag_usecase.NewTagUsecase(postgresTagRepository)
	postgresTagAssignmentRepository := tag_repository.NewPostgresTagAssignmentRepository(pool)
	tagAssignmentUsecase := tag_usecase.NewTagAssignmentUsecase(postgresTagAssignmentRepository)
	tagHandler := tag_http.NewTagHandler(tagUsecase, tagAssignmentUsecase)
	// Search
	postgresSearchRepository := search_repository.NewPostgresSearchRepository(pool)
	searchUsecase := search_usecase.NewSearchUsecase(postgresSearchRepository)
	searchHandler := search_http.NewSearchHandler(searchUsecase)
	echoEcho, err := newEchoServer(cfg, userHandler, visitorEventHandler, telegramAuthHandler, sessionHandler, analyticsHandler, sessionUsecaseImpl, userService, abacEngine, courseHandler, moduleHandler, lessonHandler, categoryHandler, tagHandler, categoryNavigationHandler, searchHandler)
	if err != nil {
		return nil, err
	}
	return echoEcho, nil
}

// Для middleware и background job'ов
func InitializeSessionUsecase(cfg *config.Config) (usecase.SessionUsecase, error) {
	pool := db.ConnectPostgres(cfg)
	postgresSessionRepository := repository.NewPostgresSessionRepository(pool)
	sessionUsecaseImpl := usecase.NewSessionUsecase(postgresSessionRepository)
	return sessionUsecaseImpl, nil
}